AllCops:
  Exclude:
    - '.*'
    - '**/spec/**/*'
    - '**/coverage/**/*'
    - 'bin/**/*'
    - 'config/routes.rb'
    - 'db/**/*'
    - 'log/**/*'
    - 'org/**/*'
    - 'tmp/**/*'
    - 'public/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 110
