AllCops:
  Exclude:
    - '.*'
    - 'apps/lender_submission/spec/**/*'
    - 'bin/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'engines/pdf_exporter/spec/**/*'
    - 'engines/referral_sources/spec/**/*'
    - 'log/**/*'
    - 'org/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'

# Increased line length based on Githubs character limit per line
Metrics/LineLength:
  Max: 110
